"""empty message

Revision ID: da5d16943747
Revises: 
Create Date: 2021-07-20 16:38:41.947107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5d16943747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('property_taxes', sa.DECIMAL(asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('county',
    sa.Column('county_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('property_taxes', sa.DECIMAL(asdecimal=False), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('county_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('county')
    op.drop_table('state')
    # ### end Alembic commands ###
